version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/my-app
  - source: scripts/          # Include the scripts directory
    destination: /home/ec2-user/my-app/scripts/  # Ensure it copies to the correct location

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ec2-user

  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: ec2-user


