version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/my-app
    overwrite: yes

hooks:
  BeforeInstall:
    - location: /home/ec2-user/my-app/scripts/before_install.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: /home/ec2-user/my-app/scripts/install_dependencies.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: /home/ec2-user/my-app/scripts/start_application.sh
      timeout: 300
      runas: root




