version: 0.2

phases:
  install:
    commands:
      - echo "Installing necessary tools..."
      - npm install -g snyk
      - echo "Snyk installation complete."

  pre_build:
    commands:
      - echo "Installing project dependencies..."
      - npm install
      - echo "Dependencies installed."
      - echo "Fetching Snyk token from Secrets Manager..."
      - export SNYK_TOKEN=$(aws secretsmanager get-secret-value --secret-id snyk-api-token --query SecretString --output text | jq -r '.SNYK_TOKEN')
      - echo "Snyk token fetched successfully."
      - snyk auth $SNYK_TOKEN
      - echo "Snyk authentication complete."

  build:
    commands:
      - echo "Running Snyk vulnerability test..."
      - snyk test
      - snyk monitor
      - echo "Snyk test and monitor completed."

artifacts:
  files:
    - '**/*'
  discard-paths: yes
